# Trigger
language: android

jdk:
 - oraclejdk8

android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -verbose
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - cat out.txt
  
after_success:
  - cat out.txt

after_failure:
  - cat out.txt

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

notifications:
  email: false

sudo: false
